# Generated by Django 2.2.3 on 2019-07-17 15:01

import app_ecommerce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='product.jpg', upload_to=app_ecommerce.models.get_file_path),
        ),
    ]
