# Generated by Django 2.2.3 on 2019-07-18 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ecommerce', '0002_auto_20190717_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
